Supply and Demand Graphs
ImperialCollegeLondon/gridlington-vis pull request #40
Opened 2023-08-31 13:13 UTC by CWestICL

# Description

Replaces `plot2.py` with `supplydemand.py`, containing 4 graphs using Opal data.

Couldn't figure out how to properly import Opal data from separate file (`app/opal.py`), so raw data is stored in `supplydemand.py` for now.

Close #29

2023-09-01 17:54 UTC, AdrianDAlessandro requested changes
This is a good starting point. I will want to get rid of the header/table of contents and clean things up and make each page adapt to the screen size a bit better (basically so there is never a scroll bar).

The main thing I'd like to add here is the ability for the graphs to update as the data fills in. Obviously for now that won't do anything. but getting the functionality in would be good.

2023-09-01 17:54 UTC, AdrianDAlessandro commented on app/pages/supplydemand.py
> +    return dict(x=[[x[index]]], y=[[y[index]]]), [0], 10
This is raising an error because "graph2" doesn't exist. Can you write a callback for each of the graphs to update periodically the way this does? Just get the most recent data and re-plot it.

2023-09-01 17:54 UTC, AdrianDAlessandro commented on app/pages/supplydemand.py
> +)
Can you find a way to label the time on this figure? Since the rest of them are line graphs with a time axis, knowing the time the pie chart is displaying would be useful.

2023-09-01 17:54 UTC, AdrianDAlessandro commented on app/pages/supplydemand.py
> +# Example app.
If these lines / variables are not needed, delete them

2023-09-11 14:47 UTC, CWestICL commented
I think (one of?) the reasons the CI is failing is that mypy is having an issue with `dash.register_page(__name__)`.

![image](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/108276827/cd693026-f74e-44a5-bcd9-c67f161ba38d)

The other plots are currently using the same dash method so I'm not sure why mypy isn't happy with this one.

I've included some functionality to demonstrate the updating graph data. You can run this by running the DataHub Uvicorn server at `http://127.0.0.1:8000` and then running the dash app.

2023-09-13 14:29 UTC, AdrianDAlessandro approved these changes
Great. Got it working with the periodically updating graphs. This is a good template to base off for the other views, although I think the next priority is to move the datahub API requests into a re-usable module that can be used in those other views.

Also, this will need tests and docstrings, but I think a final clean up with all of that can be done later, once all the views are complete. I will open an issue.

2023-09-13 14:29 UTC, merged