Controller View
ImperialCollegeLondon/gridlington-vis pull request #50
Opened 2023-10-04 13:26 UTC by CWestICL

Layout and placeholder functions for Controller View.

Closes #36

2023-10-04 13:27 UTC, CWestICL commented
Opened in draft as I've created a separate callback function for each button. This creates `mypy` and `ruff` errors as the `update_data` function is defined multiple times. Is there a better way to do this?

2023-10-05 17:03 UTC, AdrianDAlessandro requested changes
This looks really good, I've got some functionality changes and some quality of life changes I'm suggesting.

I think also we need to make it so that logging is captured in the docker compose logs (like we did with the datahub). I will open a new issue for that.

2023-10-05 17:03 UTC, AdrianDAlessandro commented on app/pages/control.py
> +    """Placeholder function for Save Button."""
I think I forgot to mention that the [Whimsical board](https://whimsical.com/idles-LP5cXQpyXNxtqA8fr6BKA9) contains the details of what these buttons should do. Can you change the function names and docstrings for these to more closely match those? Also, can you include more inputs/function parameters you think these callbacks might need?

(Also, I don't think we need the [square brackets] around `Input` anymore)

For example, this one could be:

```suggestion
@callback(
    Output("button_save", "children"),
    Input("button_save", "n_clicks"),
    State("Hub01_dropdown", "value"),
    etc...
)
def update_displays_button_click(n_clicks, hub01):  # type: ignore # noqa
    """Placeholder function for the Update Displays Button."""
```

2023-10-09 16:57 UTC, AdrianDAlessandro requested changes
If you can just make one more change by getting rid of the `section_data` variable you introduced and instead changing `INIT_SECTIONS` into a dictionary, I'll be happy to approve and merge this.

2023-10-09 16:57 UTC, AdrianDAlessandro commented on app/pages/control.py
> +    return default
I believe if `INIT_SECTIONS` is changed into a dictionary (as described in another comment) this will need to change a bit. But I think the whole function will be able to be replaced by a more straight-forward use of the dictionary

2023-10-09 16:57 UTC, AdrianDAlessandro commented on app/pages/control.py
> +def update_button_click(
I didn't mean to combine all the callbacks into one, but this works! I'll leave it like this for now and change it if it causes any issues later.

2023-10-11 10:33 UTC, AdrianDAlessandro commented on app/pages/control.py
> +def update_button_click(
Ah yes, that makes sense. I believe there are ways around that, but happy with this for now

https://dash.plotly.com/duplicate-callback-outputs

2023-10-11 11:57 UTC, AdrianDAlessandro approved these changes

2023-10-11 11:57 UTC, merged