Add market view page
ImperialCollegeLondon/gridlington-vis pull request #58
Opened 2023-11-03 08:46 UTC by tsmbland

# Description

Close #34 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [x] All tests pass (`python -m pytest`)
- [x] Pre-commit hooks run successfully (`pre-commit run --all-files`)

2023-11-03 08:52 UTC, tsmbland commented
I think everything's sorted in terms of the layout of the page, however I need a bit of help with the figures as it's not all clear to me what you want to show. Some of the figures are filled with dummy data for now

2023-11-03 10:54 UTC, AdrianDAlessandro requested changes

2023-11-03 10:54 UTC, AdrianDAlessandro commented on app/pages/market.py
> +    new_df = pd.DataFrame(**data)
Double this up with DSR data - call `datahub.get_dsr_data()` check what the return type is and treat it accordingly

2023-11-03 10:54 UTC, AdrianDAlessandro commented on app/figures.py
> +                    ),
This is fine as is for now - just to make it more configurable, move the header `values` to a variable and then iterate over it for assigning the cells `values`

2023-11-03 10:54 UTC, AdrianDAlessandro commented on app/pages/market.py
> +    dsr_commands_fig = generate_dsr_commands_fig(new_df)
Use the DSR data for this

2023-11-03 10:54 UTC, AdrianDAlessandro commented on app/core_api.py
> +            "states": {"load": {"url": f"{PLOT_URL}/market"}},
Replace the value of the the plot url in the existing Market and delete this

2023-11-03 11:31 UTC, tsmbland commented
I just get an empty list when I run datahub.get_dsr_data() - any ideas?

2023-11-03 15:02 UTC, tsmbland commented
Ok thanks! For the final figure the appropriate columns seem to be in Opal but not DSR. What should I do here?

2023-11-07 17:51 UTC, tsmbland commented
This is about all I can do on this for now. I've marked all the outstanding issues in the code with XXX. I'll return when the relevant data is available, as discussed today

2023-11-09 18:21 UTC, AdrianDAlessandro requested changes
Some suggestions, some things that should be deferred for later

2023-11-09 18:21 UTC, AdrianDAlessandro commented on app/figures.py
> +        dsr_commands_fig = px.line(
When I tried this with some data I got this error:

`ValueError: Plotly Express cannot process wide-form data with columns of different type.`

2023-11-09 18:21 UTC, AdrianDAlessandro commented on app/pages/market.py
> +    new_df_dsr = pd.DataFrame(**data_dsr)
This DSR data step is giving an error because it's not returning in the right format. The `datahub.get_dsr_data()` needs to be fixed but is being blocked by the fact the DSR data isn't fully understood yet. I suggest commenting it out and marking it as a todo

2023-11-10 10:24 UTC, tsmbland commented on app/figures.py
> +        dsr_commands_fig = px.line(
I think this was due to a rogue comma - should be fixed now

2023-11-10 16:30 UTC, AdrianDAlessandro requested changes
This is what this page looks like with some realistic data. Can you adjust the vertical axes limits to fit these data in them (with a bit of buffer)?

One thing I noticed is that the balancing market and the intraday graphs both had their y-axes adjust to fit the data despite the range being set to [0, 1] (comment on suspect line)

Note that the double y axes don't have their zero values lined up, which I assume is not what we want - probably means that all need to be symmetrical about zero. Also, it's not clear to me which line is for which of those axes, can you figure out a way to make that clearer?

![Screenshot 2023-11-10 at 16 21 20](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/65301412-3f43-4420-b735-c592eeb7f4df)

2023-11-10 16:30 UTC, AdrianDAlessandro commented on app/figures.py
> +        .update_traces(yaxis="y2")
I think this update traces overrides the `range_y` values

2023-11-15 10:18 UTC, AdrianDAlessandro requested changes
Update the callback to be able to use the example data.

Also, a small comment about using more explicit variable names.

2023-11-15 10:18 UTC, AdrianDAlessandro commented on app/figures.py
> +    columns = [
Really small style bugbear. Probably better to just name the variable `left_axis_columns` instead of using a comment and a vague variable name you overwrite later on
```suggestion
    left_axis_columns = [
```

2023-11-15 10:18 UTC, AdrianDAlessandro commented on app/figures.py
> +    columns = [
Same here
```suggestion
    right_axis_columns = [
```

2023-11-15 10:18 UTC, AdrianDAlessandro commented on app/pages/market.py
> +    # new_df_dsr = pd.DataFrame(**data_dsr)
To make this work with the example data, you will need to update this to match what is now in the `supplydemand.py` file or abstract out that part of code and make it part of it's own module. In fact, that's probably worth it's own PR - creating a `data.py` that holds the data that all the plots share.

2023-11-15 12:35 UTC, AdrianDAlessandro requested changes
Ok this is really good! I'd like one more change. Can you fix the values of the x-axis too?

2023-11-15 12:58 UTC, tsmbland commented
Like this? I've just hard-coded the max timepoint in the example data for now

2023-11-15 13:22 UTC, AdrianDAlessandro approved these changes
Yes, happy with this now.

There is a change in #64 that might make the time axis range values need to change. Also, can you open an Issue for each of the graphs that are still not using proper data?

2023-11-15 13:26 UTC, merged