Agent
ImperialCollegeLondon/gridlington-vis pull request #59
Opened 2023-11-03 17:16 UTC by tsmbland

# Description

So far just created an outline. Still to do:
- populate figure functions
- check layout and adjust if necessary

Close #35 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass (`python -m pytest`)
- [ ] Pre-commit hooks run successfully (`pre-commit run --all-files`)

2023-11-13 10:33 UTC, AdrianDAlessandro commented
If we remove the SVGs we should remember to squash and merge when we merge this

2023-11-17 17:25 UTC, AdrianDAlessandro requested changes
This looks really good. A few changes suggested.

2023-11-17 17:25 UTC, AdrianDAlessandro commented on app/svg.py
> +    counts = np.random.randint(0, 100, len(x_coordinates))
Can you abstract this into this function you mention but put in the docstring that it needs to be changed and open an issue for that? Maybe even link that issue in the docstring.

Same for the other function(s) like this.

2023-11-20 10:59 UTC, tsmbland commented on app/figures.py
> +        agent_activity_breakdown_fig = px.pie()
I can see there's a separate issue for this so I'll leave this for now, but happy to take on that issue

2023-11-21 19:21 UTC, AdrianDAlessandro approved these changes
This is really good, I'm happy to merge it now

2023-11-21 19:22 UTC, merged