Move titles to graphs
ImperialCollegeLondon/gridlington-vis pull request #93
Opened 2023-11-28 17:52 UTC by tsmbland

# Description

Moving titles to graphs rather than having them as their own div. Also set up some decorators to abstract some of the figure formatting. I've now set the total figure height in the market and supplydemand views to 100% to eliminate the black bar. I've left agent for now for reasons outlined below (also because layout for agent view is still tbd).

Also moving some figure formatting commands outside of if statements so things like axis labels and titles show even when the data is empty (i.e. upon startup)

Still to do:
- Sort out titles for SVGs

Close #81 
Close #62 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass (`python -m pytest`)
- [ ] Pre-commit hooks run successfully (`pre-commit run --all-files`)

2023-11-29 12:43 UTC, AdrianDAlessandro requested changes
Lot's of good things in this. I like the decorator choice, much more configurable.

I'm seeing grey columns in-between the figures and there are no longer the equivalent rows dividing them, which looks odd. We either need to remove the horizontal buffer in the rows creating that grey column, or add in a little buffer space vertically.

On your tbd points:
- I'm not touching the marketsreserve figures yet so I don't cause conflicts with the other pull request - fair
- Not sure how best to define titles for the SVGs - might just have to keep using divs for these Maybe look into using Plotly to display an SVG instead of using the HTML object? Or use a figure caption instead of a title.
- Pies and waffles were using the title attribute previously to display the time. I've remove this to show the figure title, but we may want to reintroduce e.g. as a text object. Yes, try and include this text somewhere, preferably within the Plotly object so the font is consistent etc

2023-11-29 12:43 UTC, AdrianDAlessandro commented on app/figures.py
>  time_range = ["2035-01-22 00:00:00", "2035-01-22 00:07:01.140"]
Can you update this time range to go from "2035-01-22 04:00:00.000" to "2035-01-22 11:01:08.400"? I pushed directly to main when I updated the time step in the pre-set data.

```suggestion
time_range = ["2035-01-22 04:00:00", "2035-01-22 11:01:08.400"]
```

2023-11-29 12:43 UTC, AdrianDAlessandro commented on app/figures.py
> +    # title_text=df.iloc[-1]["Time"],
Is this here for any reason?
```suggestion
```

2023-11-29 12:43 UTC, AdrianDAlessandro commented on app/figures.py
> +    total_gen_fig.layout.yaxis.range = [-5, 70]
Would be nice to add this into a decorator too

2023-11-29 12:43 UTC, AdrianDAlessandro commented on app/figures.py
> +    """Decorator for common formatting of time-series line graphs.
Maybe change this into an `axes_labels` decorator to include the y axes and any alternative options for the x axis? Would also be good if you could make the size adjustable?

2023-11-29 12:43 UTC, AdrianDAlessandro commented on app/figures.py
> +        intraday_market_sys_fig_right = (
I'm guessing this will not play nicely with my suggestion to use a decorator for the axes labels. Let's ignore this case for now because I think Phil wants to remove the double axis plots anyway

2023-11-29 12:50 UTC, AdrianDAlessandro commented on app/figures.py
>  time_range = ["2035-01-22 00:00:00", "2035-01-22 00:07:01.140"]
I see you already have this change in the Wesim PR #89

2023-11-29 13:42 UTC, tsmbland commented on app/figures.py
> +                title_x=0.5,
This is to centre the titles

2023-11-29 13:45 UTC, tsmbland commented on app/figures.py
> +        title_size (float | int, optional): Title size. Defaults to 30.
The type ignore was because I was getting "error: Missing type parameters for generic type "Callable"  [type-arg]". I can probably fix but was just being lazy

2023-11-29 13:53 UTC, tsmbland commented on app/figures.py
> +        title_size (float | int, optional): Title size. Defaults to 30.
Actually I'm just remembering the pain I went through yesterday to try and fix this before eventually giving up. Do you have any ideas how I should deal with this?

2023-11-29 15:09 UTC, AdrianDAlessandro commented on app/figures.py
> +        title_size (float | int, optional): Title size. Defaults to 30.
Ah ok - yea ignore it. Just make it `type: ignore[type-arg]` to only ignore that specific error

2023-11-29 16:44 UTC, tsmbland commented
I think this is ready now. The grey column issue is fixed in the grid layout PR. I'm going to sort out titles for SVGs in another PR to avoid conflicts

2023-11-29 17:37 UTC, AdrianDAlessandro requested changes
This is looking really good.

I've got this situation where the intraday market system and balancing market graphs no longer have a fixed x-axis range. The order in which properties are being updated on that should probably be switched.
![Screenshot 2023-11-29 at 17 35 36](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/d93fd9c0-df63-48a0-9ed0-ce435e4dcf57)

2023-11-29 17:38 UTC, AdrianDAlessandro commented
Also, I think the position of the time-stamp needs revising
![Screenshot 2023-11-29 at 17 37 44](https://github.com/ImperialCollegeLondon/gridlington-vis/assets/40875798/945f1559-73c0-4891-bee3-9f0290450a18)

2023-11-30 11:03 UTC, AdrianDAlessandro approved these changes

2023-11-30 11:04 UTC, merged